services:
  exporter:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: infrahub-exporter:latest
    environment:
      - INFRAHUB_exporter_LOG_LEVEL=INFO
      - exporter_CONFIG=/app/config.yml
      - OTEL_METRIC_EXPORT_INTERVAL=30000
    volumes:
      - ../examples/config.yml:/app/config.yml:ro
      - ../examples/queries:/app/examples/queries:ro
    ports:
      - "8001:8001"
    networks:
      - infrahub_default

  otel-collector:
    deploy:
      replicas: 0
    image: otel/opentelemetry-collector-contrib:0.128.0
    volumes:
      - ../examples/otel.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - infrahub_default

networks:
  infrahub_default:
    external: true
